x = 10
def error():
    raise ValueError
def add(one,two):
    pass 